import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'questions_answers_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'questions_answers_model.g.dart';

@freezed
class QuestionsAnswersModel with _$QuestionsAnswersModel {
  const factory QuestionsAnswersModel({
    String? question,
    String? answer,
    String? enable,
  }) = _QuestionAnswerModel;

  factory QuestionsAnswersModel.fromJson(Map<String, Object?> json) =>
      _$QuestionsAnswersModelFromJson(json);
}
