import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'QuestionAnswerModel.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'QuestionAnswerModel.g.dart';

@freezed
class QuestionAnswerModel with _$QuestionAnswerModel {
  const factory QuestionAnswerModel({
    String? question,
    String? answer,
    String? enable,
  }) = _QuestionAnswerModel;

  factory QuestionAnswerModel.fromJson(Map<String, Object?> json) =>
      _$QuestionAnswerModelFromJson(json);
}
